sudo: true
language: python
services:
  - docker
python:
  - "2.7"
  - "3.7"
install:
  - sudo pip install --upgrade docker-compose
  - pip install tox-travis
  - AZ_REPO=$(lsb_release -cs)
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - curl -L https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install apt-transport-https azure-cli
  - az extension add --name azure-cli-iot-ext
  - az --version
  - printenv
script: sudo `which tox`
